<?php
// Copyright (c) 2013 Femi Veys


// Very useful: http://drupal.org/project/1158878

function tf_feedback_init() {
  drupal_add_library('system', 'ui.draggable');
}

function tf_feedback_menu() {
  $items = array();

  $items['feedback'] = array(
    'title' => 'Feedback',
    'type' => MENU_CALLBACK,
    'page callback' => 'feedback',
    'file' => 'overview.inc',
    'access arguments' => array('access tf_feedback'),
  );

  $items['feedback/person'] = array(
    'title' => t('Person Details'),
    'type' => MENU_CALLBACK,
    'page callback' => 'person_details',
    'file' => 'person_details.inc',
    'access callback' => 'tf_is_own',
    'access arguments' => array(2),
  );

  $items['feedback/evaluate'] = array(
    'title' => 'Evaluate',
    'type' => MENU_CALLBACK,
    'page callback' => 'add_evaluation',
    'access arguments' => array('access content'),
    'file' => 'person_details.inc',
    'access callback' => 'tf_is_own',
    'access arguments' => array(2),
  );

  $items['feedback/person/%/edit'] = array(
    'title' => t('Edit Person'),
    'type' => MENU_CALLBACK,
    'page callback' => 'person_edit',
    'page arguments' => array(2),
    'access arguments' => array('access content'),
    'file' => 'person_edit.inc',
    'access callback' => 'tf_is_own',
    'access arguments' => array(2),
  );

  $items['feedback/person/%/ajax/remark'] = array( // %5 is redirect type
    'title' => 'Add remark',
    'type' => MENU_CALLBACK,
    'page callback' => 'edit_remark',
    'page arguments' => array(2, 5, 6),
    'access arguments' => array('access content'),
    'file' => 'overview.inc',
    'access callback' => 'tf_is_own',
    'access arguments' => array(2),
  );

  // Assign role to person link
  $items['feedback/person/%/assign/%'] = array(
    'page callback' => 'assign_role_to',
    'page arguments' => array(2, 4),
    'type' => MENU_CALLBACK,
    'access callback' => 'tf_is_own',
    'access arguments' => array(2, 4),
  );

  // Unassign role from person link
  $items['feedback/person/%/unassign/%'] = array(
    'page callback' => 'unassign_role',
    'page arguments' => array(2, 4),
    'type' => MENU_CALLBACK,
    'access callback' => 'tf_is_own',
    'access arguments' => array(2, 4),
  );

  return $items;
}




/*
 Queries
*/
// TODO: Improve performance
// TODO: Make Campaign as parameter instead of role (=add join)
function query_evaluation_scores($evaluation) {
  $query = db_select('node', 'i'); // interpretation

  $query->leftJoin('field_data_field_ass_item_ref', 'ai', // skill or ta (assessment item)
                         'i.nid = ai.entity_id');
  $query->leftJoin('field_data_field_parent_ref', 'e', // evaluation
                     'i.nid = e.entity_id');
  $query->leftJoin('field_data_field_score', 'sc', // score
                     'i.nid = sc.entity_id');
  $query->condition('e.field_parent_ref_nid', $evaluation->nid)
        ->fields('i', array('title','changed'));
  $query->addField('e', 'field_parent_ref_nid', 'e_nid');
  $query->addField('sc', 'field_score_value', 'score');
  $query->addField('ai', 'field_ass_item_ref_nid', 'ai_nid');

  return $query->execute();
}


function get_evaluation_scores($evaluation) {
  $scores = array();

  $eval_scores = query_evaluation_scores($evaluation);
  foreach($eval_scores as $row) {
    $scores["nid-" . $row->ai_nid] = $row->score;
  }

  return $scores;
}


function get_enriched_persons() {
  $enriched_persons = array();
  $person_types = tf_get_my_persons();

  foreach($person_types as $person_type => $persons) {
    foreach($persons as $key => $person) {
      $enriched_persons[$person_type][$key] = get_enriched_person($person);
    }
  }

  return $enriched_persons;
}


// Returns and array with keys: person and roles
//   person: person node array
//   roles: array of role nodes (keyed by role-<nid>)
function get_enriched_person($person) {
  $ret = $person;
  $ret['roles'] = array();
  $ret['skills'] = array();
  $ret['talents'] = array();
  $ret['tas'] = array();
  $ret['remarks'] = array();
  $ret['evaluations'] = array();


  if(!empty($person['node']->field_role_ref['und'])) {
    $nids = flatten_nids($person['node']->field_role_ref['und']);

    foreach($nids as $nid) {
      $full_role = get_full_role($nid);

      // Enrich with the roles
      $ret['roles']["role-$nid"]['node'] = $full_role['node'];

      // Enrich with the skills
      foreach($full_role['skills'] as $skill) {
        $ret['skills']['skill-' . $skill['node']->nid] = $skill;
      }

      // Enrich with the business talents and talent attributes
      foreach($full_role['talents']['business'] as $talent) {
        $ret['talents']['talent-' . $talent['node']->nid] = $talent;
        foreach($talent['tas'] as $ta) {
          $ret['tas']['ta-' . $ta['node']->nid] = $ta;
        }
      }

      // Enrich with the behavioral talents and talent attributes
      foreach($full_role['talents']['behavioral'] as $talent) {
        $ret['talents']['talent-' . $talent['node']->nid] = $talent;
        foreach($talent['tas'] as $ta) {
          $ret['tas']['ta-' . $ta['node']->nid] = $ta;
        }
      }
    }
  }

  // Enrich with Remarks
  if(!empty($person['node']->field_remarks_ref['und'])) {
    $nids = flatten_nids($person['node']->field_remarks_ref['und']);
    $remarks = node_load_multiple($nids);
    foreach($remarks as $remark) {
      // Put the remark in the array
      $ret['remarks']['nid-' . $remark->nid]['node'] = $remark;
      $attached_to = NULL;

      // Set what the remark is attached to in the array
      if(isset($remark->field_attached_to['und'][0]['nid'])) {
        $attached_to = node_load($remark->field_attached_to['und'][0]['nid']);
      }

      if(isset($attached_to->nid)) { // TODO: Do bettter node/object check
        $ret['remarks']['nid-' . $remark->nid]['attached_to']['node'] =
                                                                   $attached_to;
      } else {
        $ret['remarks']['nid-' . $remark->nid]['attached_to'] = array();
      }
    }
  }

  // Enrich with Evaluations
  if(!empty($person['node']->field_evaluations_ref['und'])) {
    $nids = flatten_nids($person['node']->field_evaluations_ref['und']);
    $evaluations = node_load_multiple($nids);
    foreach($evaluations as $evaluation) {
      $ret['evaluations']['nid-' . $evaluation->nid]['node'] = $evaluation;
    }
  }

  return $ret;
}


function assign_role_to($person_nid, $role_nid) {
  $person = node_load($person_nid);

  $exists = FALSE;
  if(isset($person->field_role_ref['und'][0]['nid'])) {
    foreach($person->field_role_ref['und'] as $role_ref) {
      if($role_ref['nid'] == $role_nid) {
        $exists = TRUE;
        break;
      }
    }
  }

  if(!$exists) {
    $person->field_role_ref['und'][] = array('nid' => $role_nid);
  }

  node_save($person);

  drupal_goto("feedback/person/$person_nid/edit");
}

function unassign_role($person_nid, $role_nid) {
  $person = node_load($person_nid);

  if(isset($person->field_role_ref['und'][0]['nid'])) {
    foreach($person->field_role_ref['und'] as $key => $role_ref) {
      if($role_ref['nid'] == $role_nid) {
        unset($person->field_role_ref['und'][$key]);
        // Allow eventual cleanup:        break;
      }
    }
  }

  node_save($person);

  drupal_goto("feedback/person/$person_nid/edit");
}


// Fix default image bug
// See http://drupal.org/node/1438940
function tf_feedback_file_download($uri) {
  if (strpos($uri, "default_images") > 0) {
    // Check that the file exists and is an image.
    if ($info = image_get_info($uri)) {
      return array(
        // Send headers describing the image's size, and MIME-type...
        'Content-Type' => $info['mime_type'],
        'Content-Length' => $info['file_size'],
        // By not explicitly setting them here, this uses normal Drupal
        // Expires, Cache-Control and ETag headers to prevent proxy or
        // browser caching of private images.
      );
    }
    else {
      return -1;
    }
  }
}
